name: build-and-test-plugin-with-packages

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build_and_test_plugin_using_default_matrix:
    uses: korydraughn/irods_reusable_github_workflows/.github/workflows/build-and-test-plugin-with-irods-packages-matrix.yml@main
    with:
      test_against_mysql: true
      test_against_mariadb: true
